# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Not Swift For Work 
email: kevin.lindkvist@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Swift musings and a bit of math.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevinlindkvist.com" # the base hostname & protocol for your site
twitter_username: kevinlindkvist
github_username:  kevinlindkvist

# Build settings
markdown: kramdown 
include: ['_pages']
